# https://waha.devlike.pro/docs/how-to/install/
services:
  waha:
    restart: always
    # https://waha.devlike.pro/docs/how-to/engines/#docker-images
    # https://portal.devlike.pro/docker-image
    # image: devlikeapro/waha-plus
    # WAHA Core
    # image: devlikeapro/waha:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    # Add "dns" if you have a problem with resolving "web.whatsapp.com"
    dns:
      - 1.1.1.1
      - 8.8.8.8

    ports:
      - "127.0.0.1:3000:3000/tcp"

    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      - "./sessions:/app/.sessions"

      # Save media files
      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - "./media:/app/.media"

    env_file:
      - .env
    networks:
        waha-net:
          ipv4_address: 10.0.0.2
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src/
          initial_sync: true
          ignore:
            - node_modules/
  
  # ====== CHATWOOT ======= #
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env.chat ## Change this file for customized env variables
    volumes:
      - storage_data:/app/storage
    networks:
      waha-net:
        ipv4_address: 10.0.0.3

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3200:3200'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3200', '-b', '0.0.0.0']
    restart: always
    networks:
      waha-net:
        ipv4_address: 10.0.0.4
      

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
    networks:
      waha-net:
        ipv4_address: 10.0.0.5

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.chat
    networks:
      waha-net:
        ipv4_address: 10.0.0.6

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env.chat
    volumes:
      - redis_data:/data
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      waha-net:
        ipv4_address: 10.0.0.7

networks:
  waha-net:    
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
volumes:
  storage_data:
  postgres_data:
  redis_data:
  # mongodb_data: {}
  # minio_data: {}
  # pg_data: {}
